'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { ArrowRight, CalendarCheck, Check, Clock3, HeartPulse, LockKeyhole, Mail, MapPin, MessageCircle, Sparkles } from 'lucide-react'

export type HeroSectionProps = { setChatOpen: (open: boolean) => void; navigate: (id: string) => void }

export function HeroSection({ setChatOpen, navigate }: HeroSectionProps) {
  return (
<section id="home" className="relative mx-auto max-w-7xl scroll-mt-20 px-5 pb-20 pt-16 lg:px-8 lg:pb-28 lg:pt-24"><div className="pointer-events-none absolute -right-40 -top-48 h-[32rem] w-[32rem] rounded-full bg-emerald-100/70 blur-3xl" /><div className="pointer-events-none absolute -left-48 bottom-0 h-80 w-80 rounded-full bg-cyan-100/60 blur-3xl" /><div className="relative max-w-4xl"><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-4 py-2 text-xs font-semibold text-emerald-700"><Sparkles size={14} /> AI-Powered Healthcare Assistant</motion.div><motion.h1 initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="max-w-4xl font-sans text-4xl font-bold leading-[1.12] tracking-tight text-slate-900 sm:text-6xl lg:text-7xl">Smart healthcare guidance <span className="text-emerald-600">& instant</span> appointment booking.</motion.h1><motion.p initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2 }} className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Consult with your doctor 24/7, get information about clinic timings and fees, and book appointments directly — all through our specialized AI Assistant.
</motion.p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={() => setChatOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-full bg-emerald-600 px-6 py-3.5 text-sm font-semibold text-primary-foreground shadow-lg shadow-emerald-600/20 transition hover:-translate-y-0.5 hover:bg-emerald-700">Start AI Consultation <ArrowRight size={17} /></button><button onClick={() => navigate('about-doctor')} className="inline-flex items-center justify-center rounded-full border border-emerald-600 bg-background px-6 py-3.5 text-sm font-semibold text-emerald-700 transition hover:bg-emerald-50">View Doctor Profile</button></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Secure & private</span><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Available 24/7</span><span className="flex items-center gap-2"><Check size={16} className="text-emerald-600" /> Human-led care</span></div></div></section>
  )
}
